### ISSUE TITLE
Clipping Labels

### ISSUE THREAD

**Issue by deathssoul** [lmstearn/MyReels#4]
Sorry to open an issue like this but where is the archive you want me to grab? Your email server is spitting out an error when I try to respond to your email. :(

**Comment by deathssoul** [comment]
Okay, so I got around to opening this issue!

![cut_labels](https://user-images.githubusercontent.com/13917597/51824403-21502600-22b0-11e9-84f5-fb3084a279dc.png)

The labels seem to be cut off on my end. I've tested with 1920x1200 and 1280x720 resolutions (or did I misinterpret the last one?) and the results are the same.

**Comment by lmstearn** [comment]
The 1280x720 is a worry. The piccie posted is only a section of the form- is that all you are seeing?
If it is, then the old graphic libraries are not seeing your window display aright, and a multi display setups make no sense to them. Not too much can be done in that case. :(
It's worth trying [PrgLnch](https://github.com/lmstearn/PrgLnch/wiki) for lower resolutions. Having recalled from this [thread](http://www.theassimilationlab.com/forums/topic/15816-prglnch-yet-another-game-launcher/?do=findComment&comment=445545) your monitor did not appear to be 100%  WDDM compliant, there may also be other issues with the size of controls. MyReels is a VB6 program that runs well enough in native windows, but some systems and their graphic drivers may not handle the ancient twip scaling well. Just in case there is an issue with the system files installation, just D/L the installer and run it for a repair install.

**Comment by deathssoul** [comment]
Yeah, I was using PrgLaunch. That's just a segment of the window but all of the labels are like that.

Right now, I'm using the drivers that ship with Windows as I haven't gotten up the courage to try the AMD drivers yet.

**Comment by lmstearn** [comment]
Ah right, recall that your setup is a bit delicate. Is there a lowest resolution (anything above 800X600) that it doesn't clip? Sometimes changing a font in the Appearances dialog might help.
Here's mine for 1080p:
![Labels](http://www.theassimilationlab.com/forums/uploads/monthly_2019_01/large.1080p.JPG.a11bab0595c89586ac52807b671dd0e4.JPG)
Your pictures are a lot smaller- as if it could be 2160p or greater. Are they any larger for 1280x720?
Another angle is to compare AMD profiles: either:
`C:\Users\Username\AppData\Local\ATI\ACE\Profiles.xml`
or
C`:\Users\Username\AppData\Local\AMD\CN\gmdb.blb`
The second might be the better choice, as here the _ATI Profiles.xml_ is date stamped 2015!
But first, there is a bug in the code which might affect your values of fixpw, so will be posting an update. Also, will include a debug for your windows version- it's possible something in the program has gone wrong with versioning, and taking it as pre Vista which will affect things a lot.

**Comment by deathssoul** [comment]
I can try the lower resolution.

I don't think the profiles will be all that helpful since they're not
currently in use and they were last touched by the file system back in
October when I reverted back to the drivers that shipped with Windows. I
can still upload them after my meetings though.

The images were the same size for both native and 720, to answer the last
question.

**Comment by deathssoul** [comment]
The images were the same size for both native and 720, to answer the last
question.

Apologies, I'm having to reply by email due to meetings. I'll merge the two
tomorrow.

**Comment by lmstearn** [comment]
Okay, we'll focus on 1280 X 720 for the moment. Will make some code adjustments and a debug info text, available on right click of the OK button found in Device Info at the bottom of the About page.
Will post it tomorrow, and should be available on running the Updater from the Start menu then. Thanks. 👍

**Comment by deathssoul** [comment]
Sounds good. It may not be until I get back next week but I'll definitely give it a go. :)

**Comment by lmstearn** [comment]
It's all come back as to what the issue might be regarding your monitor setup. The one you use (attached to desktop) isn't the primary monitor. Back in the days when VB6 was king, there was only one monitor, so it applies the settings for the primary monitor to all the other monitors. See this [link for "HDPI" monitors](http://www.vbforums.com/showthread.php?843651-Getting-DPI&p=5141965&viewfull=1#post5141965). Might explain why the above screenshot looks the same at two different resolutions. You could try matching the resolutions of the primary and desktop monitors, and see if that makes a difference.
The driver S/W detects that MyReels is launched from the primary and shifts it over to the current monitor, and the DPI Aware routines are not activated for MyReels. It's the same thing with PrgLnch when the driver simply ignores monitor selections of PrgLnch which adhere to the different WDDM model.

**Comment by deathssoul** [comment]
I just manually set the resolution to 1280x720 for all monitors in the display settings without success (the labels were still clipping). I also do not have Eyefinity set up so this is using the default Windows handling. I think something else may be amiss but I'm not entirely sure.

**Comment by lmstearn** [comment]
Definitely something amiss 👎 It may be the driver just creates its own viewports from the virtual screen without passing their dimensions onto Windows applications. Because the pictures in the screenshot are so small, it's likely VB6 gets its dimensions from the virtual screen anyway, because it can't see how the driver has divided it up. Have AMD of late updated the driver re Windows compatibility?

**Comment by deathssoul** [comment]
Not sure, I'm still on the Windows provided drivers from 2017. :P

I can try them, though.

**Comment by deathssoul** [comment]
Apologies, I'm still working on installing the drivers. The installation keeps stopping about 80% of the way through with an error so I've been having to troubleshoot things. I suspect there's some leftovers from when I had all the issues back in September that I need to clean out for it to install correctly.

**Comment by lmstearn** [comment]
Yeah, the drivers have to be removed completely. It's a drag putting you through this, but the following program makes it easy.
https://www.guru3d.com/files-details/display-driver-uninstaller-download.html
Then in Settings, configure Windows to stop automatically downloading any new drivers, before installing the new one, although that may not be necessary in your case.
On launching MyReels, please post debug info text, available on right click of the OK button found in Device Info at the bottom of the About page. Thanks.

**Comment by deathssoul** [comment]
Okay, got the driver installed. Apparently, a Start Menu shortcut that was pointing to nothing was blocking the install. Somehow, the file it pointed to was cached somewhere even though it no longer existed, which was confusing the installer. I had to manually remove it to get the install to complete. Windows is weird.....

After doing so, the labels still clip however.

Here's the debug text:
```
Various Variables for Debugging Scaling Issues...

Operating System Vista or Later: True

Are we Admin?  False

AMD graphical software present.
resX:  2.38806, resY:  1.982906

DC width:  1920, DC height:  1200

WA width:  1920, WA height:  1160

Textwidth ratio of a Spin picture's default font
over its currently assigned game General Font, 
Times New Roman:  1

Fontsize is:  15.86325

The following control dimensions are in Twips:

Position of Spin Picture in Frame:  0
Width of Spin Picture in Frame:  2388.05961608887
Position of Spin Picture in Frame:  2098
Width of Spin Picture in Frame:  2388.05961608887
Position of Spin Picture in Frame:  4196
Width of Spin Picture in Frame:  `2388.05961608887
```

**Comment by lmstearn** [comment]
The driver update worked? Great. Sounds like you backed up and restored settings, as previously it took a bit to get all the monitors setup.
Here's my debug data for 1080p with _Fonts Scale & layout_  at 125% run through PrgLnch:
> resX:  1.910448, resY:  1.425445
> 
> DC width:  1920, DC height:  1080
> 
> WA width:  1920, WA height:  1042
> 
> Textwidth ratio of a Spin picture's default font
> over its currently assigned game General Font, 
> Times New Roman:  1
> 
> Fontsize is:  11.40356
> 
> The following control dimensions are in Twips:
> 
> Position of Spin Picture in Frame:  0
> Width of Spin Picture in Frame:  1910.44771671295
> Position of Spin Picture in Frame:  1508
> Width of Spin Picture in Frame:  1910.44771671295
> Position of Spin Picture in Frame:  3016
> Width of Spin Picture in Frame:  1910.44771671295

When we try _Fonts Scale & layout_  at 150%, for 760p, there is massive error in the TwipsPerPixelY & WA calc and the bottom edge of the form either moves up off the bottom taskbar, and some forms disappear off the bottom edge. It even gets worse when _Fonts Scale & layout_ > 150%.
However, running through PrgLnch at 1080p, things look okay, and there is:

> resX:  1.59204, resY:  1.177677
> 
> DC width:  1920, DC height:  1080
> 
> WA width:  1920, WA height:  1034
> 
> Textwidth ratio of a Spin picture's default font
> over its currently assigned game General Font, 
> Times New Roman:  1
> 
> Fontsize is:  9.421412
> 
> The following control dimensions are in Twips:
> 
> Position of Spin Picture in Frame:  0
> Width of Spin Picture in Frame:  1592.0398235321
> Position of Spin Picture in Frame:  1246
> Width of Spin Picture in Frame:  1592.0398235321
> Position of Spin Picture in Frame:  2492
> Width of Spin Picture in Frame:  1592.0398235321
> 

 But, yay, can repro when setting _Fonts Scale & layout_ at 100% there is for 1080p:

> resX:  2.38806, resY:  1.794872
> 
> DC width:  1920, DC height:  1080
> 
> WA width:  1920, WA height:  1050
> 
> Textwidth ratio of a Spin picture's default font
> over its currently assigned game General Font, 
> Times New Roman:  1
> 
> Fontsize is:  14.35897
> 
> The following control dimensions are in Twips:
> 
> Position of Spin Picture in Frame:  0
> Width of Spin Picture in Frame:  2388.05961608887
> Position of Spin Picture in Frame:  1899
> Width of Spin Picture in Frame:  2388.05961608887
> Position of Spin Picture in Frame:  3798
> Width of Spin Picture in Frame:  2388.05961608887

Funny thing is, your resY value is larger (why?), so there's even more clipping than this:
![100scaling](https://user-images.githubusercontent.com/7629854/52899827-a93ba700-3242-11e9-9d18-ec2b0b8e1435.JPG)

Looking at [La Volpes DPI thread](http://www.vbforums.com/showthread.php?816615-VB6-Tutorial-Being-DPI-Aware), he states: 

>  Label Controls. If the AutoSize property is set, during Form_Load, toggle the AutoSize from True to False and back to True.

The prize labels don't have the AutoSize property set, unfortunately, and there's a bit in doing it, along with the prospect of it not working anyhow. What can be done easily is to size the labels fractionally larger vertically.
Edit: Uploaded a new version with a fixed manifest, but no difference. The labels and pictures just don't scale which might be some kind of issue with the form load or form show. What's stranger is the font height is supposed to be less in the prize amount labels than in the prize indicators. With the current exe, could you post a screenshot of the screen from "Edit Reel Combinations". Is it similar to the one in the latest update?
What's your debug output for 1280 X 720- or better, 760p (via PrgLnch)? Is there any improvement for 1080p with _Fonts Scale & layout_ at 125%?

**Comment by deathssoul** [comment]
Apologies, the last few days have been rather harrowing.

Yeah, I've been forgoing full Eyefinity since those modes don't have good support with the base operating systems and have been just activating them on a per-application basis.

What exactly do resX and resY represent? I'm confused as to what the readouts mean.

Scaling is set to 100% so I'm not sure why it's reading 125%. Maybe something is off with the calculations that the VB script is reporting?

Here's 1280x720:

```
Various Variables for Debugging Scaling Issues...

Operating System Vista or Later: True

Are we Admin?  False

AMD graphical software present.
resX:  2.38806, resY:  1.982906

DC width:  1920, DC height:  1200

WA width:  1920, WA height:  1160

Textwidth ratio of a Spin picture's default font
over its currently assigned game General Font, 
Times New Roman:  1

Fontsize is:  15.86325

The following control dimensions are in Twips:

Position of Spin Picture in Frame:  0
Width of Spin Picture in Frame:  2388.05961608887
Position of Spin Picture in Frame:  2098
Width of Spin Picture in Frame:  2388.05961608887
Position of Spin Picture in Frame:  4196
Width of Spin Picture in Frame:  2388.05961608887
```

Strange thing is that the debug output doesn't change with resolution. I think it may be reading the monitor as opposed to the OS information.

Where's "Edit Reel Combinations"? I'm not seeing that option.

Also, how would I go about building the program? I'm not seeing VB libraries in the current stable VS, do I need a different program?

**Comment by lmstearn** [comment]
Thanks.
_Fonts Scale & layout_ is a settings in the Windows display. (Depending on the display), typically offer 100% or 125%- for any others one has to logout for the changes to come into effect. I recently changed mine back to 100% to repro the clipping in the last posted screenshot.
resX & resY are scaled factors dependent on resolution.
Yeah, that's the driver. VB6 only interfaces to WDDM based calls.
"Edit Reel Combinations" is one of the buttons in the configuration menu. Does that show up in the right-clicked game popup menu?
The situation is that the dimensions of some controls (e.g.) on the form are not reflected in the ShowWindow method. Some are- e.g. fonts. But the controls are moved to their new positions in the display without issue. More tests have to be carried out!
Can't be built with VS. Only with the VB IDE. But there are some replacement projects around.

**Comment by deathssoul** [comment]
Windows won't let me select a different scaling factor for a non-native resolution. /shrug

Here's the configuration screen:

![edit_reel_combinations](https://user-images.githubusercontent.com/13917597/53158789-7242f980-3592-11e9-87a4-08b883464ee1.PNG)

Okay, I don't think I still have my old VB6 disks but I'll dig through some boxes. I'm pretty sure they got lost in a move, though.

**Comment by lmstearn** [comment]
That's probably more the driver than Windows- it can on this Radeon 7700, but thanks for checking.
Thanks, shot looks good, everything scales nicely there.
Hey, that would be great, if not, it's easy to vote:
https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/12516426-allow-free-download-of-the-vb6-programming-languag
As VB6 programs are still supported, they still want the dosh for it.
Anyhow, posting an update fix tomorrow night,- and will attempt to keep intact all the working scalability for previous OSes. As we are building on the XP machine, that won't be difficult to test!

**Comment by lmstearn** [comment]
Update loaded. Things are better here, but there may still be a bit of clipping on yours.
Some form components aren't properly scaled- e.g. the drivelists and quote text. Other forms don't have any scaling at all, but that can wait for later. :)

**Comment by deathssoul** [comment]
Got a new issue: the update checker is not detecting the new release.

**Comment by lmstearn** [comment]
~~What's the version of the Updater you have in the MyReels directory? It's supposed to be 3.3.0- did it get overwritten somehow?~~
Eccch: nvm- updated the version file, sorry.

**Comment by deathssoul** [comment]
That fixed the clipping and updater. What's next?

**Comment by lmstearn** [comment]
All the forms look passable? Great, we're done! :)
Tomorrow, intending to update PrgLnch before moving onto FuzzyQuasiSKSE. :)

**Comment by deathssoul** [comment]
They're presentable but the alignment is a bit off. Probably not worth worrying about, though. :)
